// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: iam/accesscontroller/v1alpha1/write_service.proto

package acl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationTupleDelta_Action int32

const (
	// Unspecified.
	// The `WriteRelationTuplesTxn` rpc ignores this
	// RelationTupleDelta if an action was unspecified.
	RelationTupleDelta_ACTION_UNSPECIFIED RelationTupleDelta_Action = 0
	// Insertion of a new RelationTuple.
	// It is ignored if already existing.
	RelationTupleDelta_INSERT RelationTupleDelta_Action = 1
	// Deletion of the RelationTuple.
	// It is ignored if it does not exist.
	RelationTupleDelta_DELETE RelationTupleDelta_Action = 4
)

// Enum value maps for RelationTupleDelta_Action.
var (
	RelationTupleDelta_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "INSERT",
		4: "DELETE",
	}
	RelationTupleDelta_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"INSERT":             1,
		"DELETE":             4,
	}
)

func (x RelationTupleDelta_Action) Enum() *RelationTupleDelta_Action {
	p := new(RelationTupleDelta_Action)
	*p = x
	return p
}

func (x RelationTupleDelta_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationTupleDelta_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_accesscontroller_v1alpha1_write_service_proto_enumTypes[0].Descriptor()
}

func (RelationTupleDelta_Action) Type() protoreflect.EnumType {
	return &file_iam_accesscontroller_v1alpha1_write_service_proto_enumTypes[0]
}

func (x RelationTupleDelta_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationTupleDelta_Action.Descriptor instead.
func (RelationTupleDelta_Action) EnumDescriptor() ([]byte, []int) {
	return file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescGZIP(), []int{1, 0}
}

// The request of a WriteService.WriteRelationTuplesTxn rpc.
type WriteRelationTuplesTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The write delta for the relation tuples operated in one single transaction.
	// Either all actions commit or no changes take effect on error.
	//
	// The tuple's etag is used for a consistent read-modify-write request flow.
	// If the etag is not present, the tuple is not validated against the state
	// of the serverside tuple.
	RelationTupleDeltas []*RelationTupleDelta `protobuf:"bytes,1,rep,name=relation_tuple_deltas,json=relationTupleDeltas,proto3" json:"relation_tuple_deltas,omitempty"`
}

func (x *WriteRelationTuplesTxnRequest) Reset() {
	*x = WriteRelationTuplesTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRelationTuplesTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationTuplesTxnRequest) ProtoMessage() {}

func (x *WriteRelationTuplesTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationTuplesTxnRequest.ProtoReflect.Descriptor instead.
func (*WriteRelationTuplesTxnRequest) Descriptor() ([]byte, []int) {
	return file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRelationTuplesTxnRequest) GetRelationTupleDeltas() []*RelationTupleDelta {
	if x != nil {
		return x.RelationTupleDeltas
	}
	return nil
}

// Write-delta for a WriteRelationTuplesTxnRequest.
type RelationTupleDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The action to do on the RelationTuple.
	Action RelationTupleDelta_Action `protobuf:"varint,1,opt,name=action,proto3,enum=iam.accesscontroller.v1alpha1.RelationTupleDelta_Action" json:"action,omitempty"`
	// The target RelationTuple.
	RelationTuple *RelationTuple `protobuf:"bytes,2,opt,name=relation_tuple,json=relationTuple,proto3" json:"relation_tuple,omitempty"`
}

func (x *RelationTupleDelta) Reset() {
	*x = RelationTupleDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationTupleDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTupleDelta) ProtoMessage() {}

func (x *RelationTupleDelta) ProtoReflect() protoreflect.Message {
	mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTupleDelta.ProtoReflect.Descriptor instead.
func (*RelationTupleDelta) Descriptor() ([]byte, []int) {
	return file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescGZIP(), []int{1}
}

func (x *RelationTupleDelta) GetAction() RelationTupleDelta_Action {
	if x != nil {
		return x.Action
	}
	return RelationTupleDelta_ACTION_UNSPECIFIED
}

func (x *RelationTupleDelta) GetRelationTuple() *RelationTuple {
	if x != nil {
		return x.RelationTuple
	}
	return nil
}

// The response of a WriteService.WriteRelationTuplesTxn rpc.
type WriteRelationTuplesTxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of the new latest snapshot tokens of the affected RelationTuple,
	// with the same index as specified in the `relation_tuple_deltas` field of
	// the WriteRelationTuplesTxnRequest request.
	//
	// If the RelationTupleDelta_Action was DELETE
	// the snaptoken is empty at the same index.
	Snaptokens []string `protobuf:"bytes,1,rep,name=snaptokens,proto3" json:"snaptokens,omitempty"`
}

func (x *WriteRelationTuplesTxnResponse) Reset() {
	*x = WriteRelationTuplesTxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRelationTuplesTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationTuplesTxnResponse) ProtoMessage() {}

func (x *WriteRelationTuplesTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationTuplesTxnResponse.ProtoReflect.Descriptor instead.
func (*WriteRelationTuplesTxnResponse) Descriptor() ([]byte, []int) {
	return file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRelationTuplesTxnResponse) GetSnaptokens() []string {
	if x != nil {
		return x.Snaptokens
	}
	return nil
}

var File_iam_accesscontroller_v1alpha1_write_service_proto protoreflect.FileDescriptor

var file_iam_accesscontroller_v1alpha1_write_service_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x1a, 0x27, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2f, 0x61, 0x63, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x1d,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70,
	0x6c, 0x65, 0x73, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x65, 0x0a,
	0x15, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f,
	0x64, 0x65, 0x6c, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x69,
	0x61, 0x6d, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52,
	0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x44, 0x65,
	0x6c, 0x74, 0x61, 0x73, 0x22, 0xf5, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x50, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x53, 0x0a,
	0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70,
	0x6c, 0x65, 0x22, 0x38, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x12,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x22, 0x40, 0x0a, 0x1e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70,
	0x6c, 0x65, 0x73, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x32, 0xa6,
	0x01, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x95, 0x01, 0x0a, 0x16, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x54, 0x78, 0x6e, 0x12, 0x3c, 0x2e, 0x69, 0x61, 0x6d,
	0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x54, 0x78,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x54, 0x78, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x5a, 0x5f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x6e, 0x2d, 0x77, 0x68, 0x69, 0x74, 0x2f, 0x7a,
	0x61, 0x6e, 0x7a, 0x69, 0x62, 0x61, 0x72, 0x2d, 0x70, 0x6f, 0x63, 0x2f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x61, 0x63, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescOnce sync.Once
	file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescData = file_iam_accesscontroller_v1alpha1_write_service_proto_rawDesc
)

func file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescGZIP() []byte {
	file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescOnce.Do(func() {
		file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescData)
	})
	return file_iam_accesscontroller_v1alpha1_write_service_proto_rawDescData
}

var file_iam_accesscontroller_v1alpha1_write_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iam_accesscontroller_v1alpha1_write_service_proto_goTypes = []interface{}{
	(RelationTupleDelta_Action)(0),         // 0: iam.accesscontroller.v1alpha1.RelationTupleDelta.Action
	(*WriteRelationTuplesTxnRequest)(nil),  // 1: iam.accesscontroller.v1alpha1.WriteRelationTuplesTxnRequest
	(*RelationTupleDelta)(nil),             // 2: iam.accesscontroller.v1alpha1.RelationTupleDelta
	(*WriteRelationTuplesTxnResponse)(nil), // 3: iam.accesscontroller.v1alpha1.WriteRelationTuplesTxnResponse
	(*RelationTuple)(nil),                  // 4: iam.accesscontroller.v1alpha1.RelationTuple
}
var file_iam_accesscontroller_v1alpha1_write_service_proto_depIdxs = []int32{
	2, // 0: iam.accesscontroller.v1alpha1.WriteRelationTuplesTxnRequest.relation_tuple_deltas:type_name -> iam.accesscontroller.v1alpha1.RelationTupleDelta
	0, // 1: iam.accesscontroller.v1alpha1.RelationTupleDelta.action:type_name -> iam.accesscontroller.v1alpha1.RelationTupleDelta.Action
	4, // 2: iam.accesscontroller.v1alpha1.RelationTupleDelta.relation_tuple:type_name -> iam.accesscontroller.v1alpha1.RelationTuple
	1, // 3: iam.accesscontroller.v1alpha1.WriteService.WriteRelationTuplesTxn:input_type -> iam.accesscontroller.v1alpha1.WriteRelationTuplesTxnRequest
	3, // 4: iam.accesscontroller.v1alpha1.WriteService.WriteRelationTuplesTxn:output_type -> iam.accesscontroller.v1alpha1.WriteRelationTuplesTxnResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_iam_accesscontroller_v1alpha1_write_service_proto_init() }
func file_iam_accesscontroller_v1alpha1_write_service_proto_init() {
	if File_iam_accesscontroller_v1alpha1_write_service_proto != nil {
		return
	}
	file_iam_accesscontroller_v1alpha1_acl_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRelationTuplesTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationTupleDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRelationTuplesTxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iam_accesscontroller_v1alpha1_write_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_accesscontroller_v1alpha1_write_service_proto_goTypes,
		DependencyIndexes: file_iam_accesscontroller_v1alpha1_write_service_proto_depIdxs,
		EnumInfos:         file_iam_accesscontroller_v1alpha1_write_service_proto_enumTypes,
		MessageInfos:      file_iam_accesscontroller_v1alpha1_write_service_proto_msgTypes,
	}.Build()
	File_iam_accesscontroller_v1alpha1_write_service_proto = out.File
	file_iam_accesscontroller_v1alpha1_write_service_proto_rawDesc = nil
	file_iam_accesscontroller_v1alpha1_write_service_proto_goTypes = nil
	file_iam_accesscontroller_v1alpha1_write_service_proto_depIdxs = nil
}
