apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-controller.fullname" . }}
  labels:
    {{- include "access-controller.labels" . | nindent 4 }}
spec:
  clusterIP: None
  # We want all Pods in the StatefulSet to have their addresses published for
  # the sake of the other CockroachDB Pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.ports.gossip.port }}
      targetPort: gossip-tcp
      protocol: TCP
      name: gossip
  selector:
    {{- include "access-controller.selectorLabels" . | nindent 4 }}
